resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: mqconsume-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
    - AzureFunctionsJobHost__telemetryMode=OpenTelemetry
    - AzureWebJobsStorage__blobServiceUri={funcstorage01d5d.outputs.blobEndpoint}
    - AzureWebJobsStorage__queueServiceUri={funcstorage01d5d.outputs.queueEndpoint}
    - AzureWebJobsStorage__tableServiceUri={funcstorage01d5d.outputs.tableEndpoint}
    - Aspire__Azure__Storage__Blobs__AzureWebJobsStorage__ServiceUri={funcstorage01d5d.outputs.blobEndpoint}
    - Aspire__Azure__Storage__Queues__AzureWebJobsStorage__ServiceUri={funcstorage01d5d.outputs.queueEndpoint}
    - Aspire__Azure__Data__Tables__AzureWebJobsStorage__ServiceUri={funcstorage01d5d.outputs.tableEndpoint}
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=mqconsume
    - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
- name: mqconsume-secrets
  envs:
  - .mqconsume.secrets
